name: "pnpm install"
description: "Installs dependencies via pnpm"
runs:
  using: "composite"
  steps:
    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.1.0

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      shell: bash

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install Dependencies
      run: pnpm install
      shell: bash
